### ISSUE TITLE
dataset "STUDENT ALCOHOL CONSUMPTION" does not appear to exist.

### ISSUE THREAD

**Issue by fstrecker** [guipsamora/pandas_exercises#10]
pandas_exercises/04_Apply/Students_Alcohol_Consumption/exercises 
refers to dataset that does no longer exist on UCI

**Comment by aquaraga** [comment]
+1
I could find the data on kaggle [here](https://www.kaggle.com/uciml/student-alcohol-consumption/downloads/student-alcohol-consumption.zip).
Nevertheless, as the above link needs a login, it would be nice to host the data somewhere else.

**Comment by guipsamora** [comment]
@fstrecker @aquaraga Thank you! I've just added the dataset.
