### ISSUE TITLE
Using nbgrader?

### ISSUE THREAD

**Issue by orbidder** [guipsamora/pandas_exercises#101]
Great exercises, thank you so much. Not really an issue but a suggestion would be to use nbgrader to check the user's answers against the solution automatically? Here's a [link](https://nbgrader.readthedocs.io/en/stable/)

**Comment by guipsamora** [comment]
Hi @orbidder thank you for the suggestion! That sounds pretty interesting, would you mind creating a pull request with a proposal using the nbgrader, so that I have a better impression on how it can be implemented in the project?
