### ISSUE TITLE
New to GitHub

### ISSUE THREAD

**Issue by anuragkotamraju** [guipsamora/pandas_exercises#105]
Hey,
I came across your pandas exercise. I am new to GitHub, how do I code in your pandas exercise and execute them? Right now they are greyed out and I am unable to edit.

**Comment by guipsamora** [comment]
Hi @anuragkotamraju , please install anaconda and run a jupyter notebook on your machine.

**Comment by karlosdaniel451** [comment]
I know it's been a long time, but you could use https://mybinder.org/.
