### ISSUE TITLE
Missing third exercise in 04_Apply

### ISSUE THREAD

**Issue by aquaraga** [guipsamora/pandas_exercises#11]
"04_Apply/US_Crime_Rates/Exercises_with_solutions.ipynb" has some questions on the 'Chipotle' data, which is not related to the US Crime rate data. See the questions from 'Step 11'.

Maybe these questions should be part of '"04_Apply/US_Crime_Rates/Chipotle'.

**Comment by guipsamora** [comment]
@aquaraga thank you for the issue. As I was making a PR on this exercise I've noticed and excluded the questions from the Chipotle exercises. Thank you again! I'd love to hear, if you have any feedback or idea on how to make this repo better!!
