### ISSUE TITLE
the link doesn't work anymore

### ISSUE THREAD

**Issue by georgeslowa** [guipsamora/pandas_exercises#16]

**Comment by guipsamora** [comment]
Hi! What link are you talking about?

**Comment by georgeslowa** [comment]
Hey sorry for the lack of context, first time I raise an issue! In the exercise Apple_Stock, you ask to get the data from an address [https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Time_Series/Apple_Stock/appl_1980_2014.csv](url) that looks dead. I think you forgot the ".../pandas_exercises/ **blob_** master/...

best,
JP

**Comment by guipsamora** [comment]
Thank you for providing the context. Actually it is the address [https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/**09_Time_Series**/Apple_Stock/appl_1980_2014.csv](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/09_Time_Series/Apple_Stock/appl_1980_2014.csv).

I will fix it. Thanks
