### ISSUE TITLE
Links to datasets in 05_Merge and 06_Stats incorrect

### ISSUE THREAD

**Issue by tsiutsiu** [guipsamora/pandas_exercises#17]
1) The links in Step 2 of 05_Merge are incorrect. 
They're:
https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars1.csv
https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars2.csv  

    They should be:
https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv
https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv

2) The link in Step 2 of 06_Stats is incorrect. Currently it's :
 https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Stats/US_Baby_Names/US_Baby_Names_right.csv

    It should be:
https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv

**Comment by guipsamora** [comment]
Thank you! I've just fixed them! 👍 😉
