### ISSUE TITLE
Chipotle Exercises Step 16 Issue

### ISSUE THREAD

**Issue by 0mdp1** [guipsamora/pandas_exercises#19]
You ask: 'What is the average amount per order?'

Your solution:
`order_grouped = chipo.groupby(by=['order_id']).sum()
order_grouped.mean()['item_price']`
output: `18.81`

But if we're talking about average amount per order, I assume that would mean the average revenue per order (quantity * price, what was computed in question 14):

`order_grouped = chipo.groupby(by=['order_id']).sum()
order_grouped.mean()['rev']`
output: `21.39`

Just a matter of semantics really. This practice set is awesome btw!

**Comment by JTBooth** [comment]
The "item price" in this example is the amount spent on all items of that type in this order. For example, 2 steak burritos has an item price of $22, but one steak burrito has item price $11. This actually manifests in some other questions - writing an issue now.

**Comment by guipsamora** [comment]
Fixed with last PRs.
