### ISSUE TITLE
Chiptole  : Finding the highest ordered item

### ISSUE THREAD

**Issue by pratapme1** [guipsamora/pandas_exercises#20]
When I tried using the following code the ordered item quantity is different
  chipo['item_name'].value_counts().head(1)
Out[48]:
Chicken Bowl    726
Name: item_name, dtype: int64

But when i try your method it is having different value.
chipo.groupby('item_name').sum().sort_values(['quantity'],ascending =False).head(1)

order_id | quantity
-- | --

713926 | 761

 can you please help me with same and explanation would very much appreciated

**Comment by JTBooth** [comment]
The groupby(...)sum() code is accounting for item_count. Chicken bowls were ordered 726 times, but 35 of those were for 2 chicken bowls.

**Comment by kartikgiri92** [comment]
chipo["item_name"] makes a series...
chipo["item_name"].value_counts....gives the number of times each item is present in that series.
Meanwhile chipo.groupby("item_name")..makes an object and then adding the sum function further to it adds the quantity column for each time the item is present.
So basically value_counts adds the number of time item is present in "item_name" column and group_by().sum() add the quantity column elements for the items.

**Comment by Serg132003** [comment]
Sorry - didn't get it. I count max using chipo['item_name'].value_counts() and got 726 items. Method, shown in exercise gives 761. When I actually check original file in excel it gives me 726 as well. What is right way to count and how did this error appear?

**Comment by guipsamora** [comment]
Fixed with last PRs.
