### ISSUE TITLE
Chipotle Item Price

### ISSUE THREAD

**Issue by JTBooth** [guipsamora/pandas_exercises#21]
In a few of the early Chipotle examples, item_price is treated as the cost of a single item. It looks to me like it's actually the cost of all items of the type in that order - the most expensive item is "2 steak burritos" at $22, but a single steak burrito only costs $11.

**Comment by jgoodbody** [comment]
I only noticed this after seeing the Step 16 revenue discrepancy. When I went back I realized this issue made Step 14 incorrect, while Step 16 is actually correct...

**Comment by jmbejara** [comment]
For reference

`chipo.query("item_name == '6 Pack Soft Drink'")`
produces

  | order_id | quantity | item_name | choice_description | item_price
-- | -- | -- | -- | -- | --
129 | 1 | 6 Pack Soft Drink | [Sprite] | 6.49
148 | 1 | 6 Pack Soft Drink | [Diet Coke] | 6.49
154 | 1 | 6 Pack Soft Drink | [Coke] | 6.49
168 | 1 | 6 Pack Soft Drink | [Diet Coke] | 6.49
182 | 1 | 6 Pack Soft Drink | [Diet Coke] | 6.49
230 | 1 | 6 Pack Soft Drink | [Diet Coke] | 6.49
...
1109 | 1 | 6 Pack Soft Drink | [Diet Coke] | 6.49
1136 | 1 | 6 Pack Soft Drink | [Diet Coke] | 6.49
1196 | 1 | 6 Pack Soft Drink | [Diet Coke] | 6.49
1248 | 1 | 6 Pack Soft Drink | [Diet Coke] | 6.49
1253 | 1 | 6 Pack Soft Drink | [Lemonade] | 6.49
1360 | 2 | 6 Pack Soft Drink | [Diet Coke] | 12.98
1373 | 1 | 6 Pack Soft Drink | [Coke] | 6.49
...

**Comment by jmbejara** [comment]
Also, items have different costs based on `choice_description`.  If we filter out items labelled as `Barbacoa Bowl`, we see this.


order_id | quantity | item_name | choice_description | item_price
-- | -- | -- | -- | --
19 | 1 | Barbacoa Bowl | [Roasted Chili Corn Salsa, [Fajita Vegetables,... | 11.75
27 | 1 | Barbacoa Bowl | [Roasted Chili Corn Salsa, [Fajita Vegetables,... | 11.75
42 | 1 | Barbacoa Bowl | [Fresh Tomato Salsa, [Fajita Vegetables, Rice,... | 9.25
51 | 1 | Barbacoa Bowl | [[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G... | 8.99
56 | 1 | Barbacoa Bowl | [Tomatillo Red Chili Salsa, [Rice, Pinto Beans... | 9.25
61 | 1 | Barbacoa Bowl | [Tomatillo Red Chili Salsa, [Fajita Vegetables... | 11.75
97 | 1 | Barbacoa Bowl | [Tomatillo Red Chili Salsa, [Rice, Black Beans... | 9.25

The current code calculates a unit price using something like this:

```python
# delete the duplicates in item_name and quantity
chipo_filtered = chipo.drop_duplicates(['item_name','quantity'])

# select only the products with quantity equals to 1
chipo_one_prod = chipo_filtered[chipo_filtered.quantity == 1]

# select only the item_name and item_price columns
price_per_item = chipo_one_prod[['item_name', 'item_price']]

# sort the values from the most to less expensive
price_per_item.sort_values(by = "item_name", ascending = True)
```

The question should probably ask to find the price, grouping by the `choice_description` or the question should probably ask for the average price of each item.

**Comment by guipsamora** [comment]
Fixed with last PRs.
