### ISSUE TITLE
04_Apply Students_Alcohol_Consumption, Step 10

### ISSUE THREAD

**Issue by mingchau** [guipsamora/pandas_exercises#26]
the age column type is np.int64, but after applymat, it returns None
As attached:
![snipaste_2018-01-12_14-21-31](https://user-images.githubusercontent.com/18564039/34862173-e9739e66-f7a3-11e7-8e13-e93d9074013b.png)

**Comment by Shan11812** [comment]
type of param passed to function is int
```
df.age.dtype => dtype('int64')
df.age.apply(lambda r: print(type(r))) => <class 'int'>
```
so function should change accordingly.
```
def times10(x):
    if type(x) is int:
        return 10 * x
    return x
```
