### ISSUE TITLE
Ex2 - Getting and Knowing your Data Step 10

### ISSUE THREAD

**Issue by cuteapi** [guipsamora/pandas_exercises#27]
Ex2 - Getting and Knowing your Data
Step 10. How many items were ordered?
the answer is same as step 9, but i think the right answer is chipo['quantity'].sum(). do i misunderstand the question?

**Comment by hwangm** [comment]
It's the same as step 9 - the name and count of the order can be found via the code from step 9:

> `x = chipo.groupby(['item_name'])['quantity'].sum().reset_index(name='quantity_ordered').sort_values(by=['quantity_ordered'], ascending=False).head(1)`

To get step 9 name of most ordered item:
`list(x['item_name'].values)[0]`

To get step 10 count of the most ordered item:
`list(x['quantity_ordered'].values)[0]`

Question is just worded less than perfectly, I think.

**Comment by guipsamora** [comment]
Fixed with last PRs.
