### ISSUE TITLE
Poor quality of "06_Stats/Wind_Stats" exercise

### ISSUE THREAD

**Issue by maxim5** [guipsamora/pandas_exercises#30]
- The link at step 2 is wrong, as it leads to github, not the data
- Steps 4 and 5 are confusing, because they depend on the way the step 3 is solved. I didn't do a mistake described in solutions and spent some time figuring out what these steps are about.
- The solution to step 7 is wrong, it should be:
`data.shape[0] - data.isnull().sum()` or better `data.notnull().sum()`.
- The solution to step 8 is wrong: the mean value does not equal to the mean of means. The right solution is:
`data.fillna(0).values.flatten().mean()`
- The solution to step 9 seems a bit verbose. What's wrong with `describe(percentiles=[])`?
- The solution to step 11 seems ok, but is too verbose as well. Pandas favors one-liners where possible:
`data.loc[data.index.month == 1].mean()`
- The solutions to steps 12, 13 and 14 are **absolutely wrong**. It has nothing to do with "yearly/monthly frequency", but selects individual rows from the data frame. The right solution looks like:
`data.groupby(data.index.to_period('A')).mean()`
- Step 15 is confusing, because that's "monthly frequency" that step 13 was about. The distinction should be better clarified in both steps. And the solution is wrong again. Here's what it should be:
`data.groupby(data.index.to_period('M')).mean().head()`

Overall, 11 out of 16 are either wrong or misleading. On top of that, the bulk of this notebook belongs to "Time series analysis"

**Comment by guipsamora** [comment]
@maxim5 Thank you for the valid inputs. It would be great if you could make a PR in order to improve the quality of it.

**Comment by TakaakiFuruse** [comment]
@guipsamora 
Do you mind if I send you a massive Pull Requests?
I'm now re-studying pandas by using your repo. What I did was just open the answer, run the notebook and read your scripts, but found tons of errors. (Currently, I went through 1 through 8 and thinking of finishing all them up.)

**Comment by TakaakiFuruse** [comment]
@guipsamora 
I did few days ago. Please have a look.

**Comment by guipsamora** [comment]
@maxim5 thank you, I implemented your suggestions. Thanks for the massive PRs @TakaakiFuruse and sorry for taking to long to merge them, I just moved to Germany and started working he so I had other priorities. Feel free to collaborate on this repo!
