### ISSUE TITLE
Massive pull requests!!

### ISSUE THREAD

**Issue by TakaakiFuruse** [guipsamora/pandas_exercises#48]
Just Fixed lots of typos and errors in "Exercise_with_solutions" parts and some for "Exercise" and "Solution" parts.

For "Exercise" and "Solution" parts, I couldn't fix all of the links or titles so far.
It might be little confusing for readers, so please grep urls or titles and fix them.

For some parts, commits are messy, because I had to execute some cells and renew the result.
Rather than checking fixes from github, for some part, checking them from Jupyter notebook would be better.

https://github.com/guipsamora/pandas_exercises/pull/37
https://github.com/guipsamora/pandas_exercises/pull/38
https://github.com/guipsamora/pandas_exercises/pull/39
https://github.com/guipsamora/pandas_exercises/pull/40
https://github.com/guipsamora/pandas_exercises/pull/41
https://github.com/guipsamora/pandas_exercises/pull/42
https://github.com/guipsamora/pandas_exercises/pull/43
https://github.com/guipsamora/pandas_exercises/pull/44
https://github.com/guipsamora/pandas_exercises/pull/45
https://github.com/guipsamora/pandas_exercises/pull/46
https://github.com/guipsamora/pandas_exercises/pull/47
https://github.com/guipsamora/pandas_exercises/pull/49

**Comment by guipsamora** [comment]
Thank you!!
