### ISSUE TITLE
02_Filtering_&_Sorting / Fictional_Army

### ISSUE THREAD

**Issue by pkro** [guipsamora/pandas_exercises#52]
According to the link below, the ix method is deprecated.

http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#deprecate-ix

Solutions for step 17 could be, for example (just what i came up with):
army.loc[['Arizona'], army.columns[3]]

and for step 18:
army.iloc[2, army.columns.tolist().index('deaths')]

Also, in step 3 the "Don't forget to include the columns names" is confusing since pd.DataFrame imports the structure fine without, just not in the order expected by the solutions of the following exercises.

Thanks for this great collection of exercises, it's a real treasure.

**Comment by guipsamora** [comment]
Hi @pkro thanks for opening this issue. Could you make a PR on these improvements? :)

**Comment by pkro** [comment]
Done. I guess these changes have to be done in the source ipynb's, correct? Doing them on the local nb server seems to add a lot of unnecessary metadata.
