### ISSUE TITLE
Count not a general solution in Chipotle, 02_Filtering_&_Sorting

### ISSUE THREAD

**Issue by josalhor** [guipsamora/pandas_exercises#63]
Step 8 proposes the following solution to count how many Veggie Salad Bowl there are.

```
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]

len(chipo_salad)
```

However this doesn't seem like a general solution to the problem. Wouldn't it be better:

`chipo[chipo.item_name == "Veggie Salad Bowl"].quantity.sum()`

So that quantities get taken into account?

**Comment by guipsamora** [comment]
The question is "Step 8. How many times were a Veggie Salad Bowl ordered?" not "Step 8. How many Veggie Salad Bowl were ordered?". Coincidentally they provide the same answer 18, but are different questions.
