### ISSUE TITLE
pandas_exercises/04_Apply/Students_Alcohol_Consumption/Exercises_with_solutions.ipynb Step 5. Capitalize

### ISSUE THREAD

**Issue by san089** [guipsamora/pandas_exercises#68]
In step 5, the exercise question says to create a function to capitalize on strings. The function applied is x.upper(). Isn't it supposed to be x.capitalize(), as a capitalizing string means to make the first character as uppercase and rest as lowercase?

```
Step 5. Create a lambda function that captalize strings.
captalizer = lambda x: x.upper()
```

Expected:

```
Step 5. Create a lambda function that captalize strings.
captalizer = lambda x: x.capitalize()
```

**Comment by guipsamora** [comment]
You are correct. I updated the exercise. Thank you!
