### ISSUE TITLE
02 Fictional Army Step Steps 9-12

### ISSUE THREAD

**Issue by bromero26** [guipsamora/pandas_exercises#73]
I think the steps 9-12, dealing with slicing with loc, need to be reworked. Some solutions do not quite match the exercise text. For example, step 12 asks for columns 3-7 (five columns), but the solution retrieves columns 5-7 (three columns)

I've found these exercises great. Thanks for putting them together

**Comment by guipsamora** [comment]
Hi Bernardo,

Thank you for the message and feedback. :) Please, feel free to submit a pull request with your improvement suggestions!

**Comment by guipsamora** [comment]
@bromero26 I have just updated the exercises with improvements! Thanks for your message.
