### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by gonulsabah** [guipsamora/pandas_exercises#77]
Hi ! I cant reach file that is train.csv for [https://github.com/guipsamora/pandas_exercises/blob/master/07_Visualization/Titanic_Desaster/Exercises_code_with_solutions.ipynb](url) .
Thank you!

**Comment by gonulsabah** [comment]
I did it :) thanx!

**Comment by gonulsabah** [comment]
you shoul update the url with [url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/07_Visualization/Titanic_Desaster/train.csv"
](url)

**Comment by guipsamora** [comment]
Fixed. Thanks for letting me know. 🙂
