### ISSUE TITLE
Wrong correction in 06_Stats/Wind_Stats/Step 8

### ISSUE THREAD

**Issue by RomanSnsk** [guipsamora/pandas_exercises#82]
Hi! Earlier you accepted corrections by this [issue](https://github.com/guipsamora/pandas_exercises/issues/30#issue-298262128) by @maxim5
But I think one of them is wrong:

> * The solution to step 8 is wrong: the mean value does not equal to the mean of means. The right solution is:
>   `data.fillna(0).values.flatten().mean()`

because when you fill NA values with 0 you distort the entire data. I think there is no reason to pick 0 or 5 or -100 to replace NA. They must be just skipped. Just like you do in rest of project when using functions like .mean(), .sum() etc. They **skip NA values by default**.

So the solution must be something like this:
`data.sum().sum() / data.notna().sum().sum()`
or this:
`data.values.flatten()[~np.isnan(data.values.flatten())].mean()`

However, I like you project and I learned a lot on it. Thank you!

**Comment by guipsamora** [comment]
@RomanSnsk thank you for your message. Could you make a PR with your suggestion?

**Comment by RomanSnsk** [comment]
@guipsamora ok, done
