### ISSUE TITLE
Type_error in python 3.7

### ISSUE THREAD

**Issue by santhoshBjeeffy** [guipsamora/pandas_exercises#86]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-a3edbf3344c1> in <module>()
----> 1 prices= [float(value[1:-1]) for value in chipo.item_price]
      2 
      3 #reassign the column values with the updated values
      4 chipo.item_price = prices
      5 

<ipython-input-15-a3edbf3344c1> in <listcomp>(.0)
----> 1 prices= [float(value[1:-1]) for value in chipo.item_price]
      2 
      3 #reassign the column values with the updated values
      4 chipo.item_price = prices
      5 

TypeError: 'float' object is not subscriptable

**Comment by guipsamora** [comment]
Hi @santhoshBjeeffy , please provide more details of which specific exercise you are referring to.

**Comment by santhoshBjeeffy** [comment]
Hi @guipsamora 

Thanks for your help in exercises.it really helped a lot..
The issue is in below file.
pandas_exercises/02_Filtering_&_Sorting/Chipotle/Exercises_with_solutions.ipynb

I have changed to below and its worked..

#clean the item price column and transform in to float
#prices= [float(value[1:-1]) for value in chipo.item_price]

#reassign the column values with the updated values
#chipo.item_price = prices

#convert thr item_price to float
chipo['item_price']=chipo['item_price'].astype(float)

#delete the duplicate in the item name and quantity
chipo_filtered=chipo.drop_duplicates(['item_name','quantity'])

#select only the quantity equal to 1
chipo_one_prod=chipo_filtered[chipo_filtered.quantity == 1]

chipo_one_prod[chipo_one_prod['item_price']>10].item_name.nunique()

Thanks & regards,
Santhosh B
