### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by twinstae** [guipsamora/pandas_exercises#88]
Hello. I want to translate the repo to Korean for korean learners.

I am a Koraean student who study data science. I think It is very useful resource to exercise Pandas. So I want to share it with korean learners.

I know. It is open-source in BSD license. I already forked it. But It is better that i notify you. Thanks for working.

**Comment by guipsamora** [comment]
@twinstae  feel free to translate it to korean! Go for it!
