### ISSUE TITLE
Completing Exercises

### ISSUE THREAD

**Issue by eak68** [guipsamora/pandas_exercises#92]
Hi - I am new to this site and am attempting to complete the exercises; however, the line where I'd enter code are not in edit form.  Am I missing something? Can you please help me figure out why I cannot add answers to the lines?

**Comment by jpaladini** [comment]
Did you download the jupyter notebook files (.ipynb)? You need those, and Jupyter, to do these.

**Comment by eak68** [comment]
I do have those downloaded, Jupter was running at the time; however, I will try again and see if it works. Thanks!
________________________________
