### ISSUE TITLE
there is some mistakes

### ISSUE THREAD

**Issue by The-Naruto** [guipsamora/pandas_exercises#99]
In
pandas_exercises-master\09_Time_Series\Getting_Financial_Data\Exercises_with_solutions_and_code

""step 4""   not work!

**Comment by alletsee** [comment]
I think the initial poster is referring to the fact that the Google Finance API is retired and not available anymore within Pandas Datareader. (The same issue for Yahoo Finance.)

It seems to me that Pandas Datareader does not currently offer access to other finance APIs that are freely accessible (without registration).

From my perspective, there might be three options.

1. Removing the exercise
2. Creating a workaround, e.g. with the "yfinance" module (that is a webscraper of Yahoo Finance)
3. Changing the exercise to an API that requires a key (it seems to me that e.g. the AlphaVantage has a relatively easy sign-up for its free tier)

I'm happy to help with those tasks if needed, but I think that it might make sense to discuss first the preferred route.

**Comment by guipsamora** [comment]
I would favor option 3 as it is possible to practice another skill, as calling from an external API.

**Comment by The-Naruto** [comment]
OK，thank you，You really helped me

**Comment by guipsamora** [comment]
@alletsee could you change the exercise so that it works with such API?
That would be awesome! 😄

**Comment by alletsee** [comment]
I could give it a shot, but I'm not an expert on those APIs from the pandas-datareader package; meaning that I probably would need some time (and trial & error) to come up with something.

**Comment by guipsamora** [comment]
No worries, we can work together on this if you would like as well

**Comment by max-alletsee** [comment]
Hi @guipsamora,

I had a bit of time and re-wrote the exercise using the AlphaVantage API to replace Google Finance, which is not supported anymore by Pandas Datareader. It's pull request #108 . It should fix the initial problem that @The-Naruto reported.
